version: "3.7"
services:
    zookeeper:
        image: "wurstmeister/zookeeper:3.4.6"
        network_mode: "host"
        restart: "unless-stopped"
    kafka:
        image: "wurstmeister/kafka:2.12-2.5.0"
        network_mode: "host"
        restart: "unless-stopped"
        depends_on:
            - "zookeeper"
        environment:
            KAFKA_LISTENERS: "PLAINTEXT://:9092"
            KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://192.168.2.100:9092"
            KAFKA_ZOOKEEPER_CONNECT: "localhost:2181"
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
            KAFKA_CREATE_TOPICS:
              "Accelerator:1:1:compact --config=segment.ms=10000 --config=min.cleanable.dirty.ratio=0.01 --config=min.compaction.lag.ms=1000,\
              AcceleratorCommand:1:1:delete --config=segment.ms=10000 --config=min.cleanable.dirty.ratio=0.01 --config=min.compaction.lag.ms=1000 --config=retention.ms=20000 --config=delete.retention.ms=1000 --config=file.delete.delay.ms=1000,\
              AcceleratorTalk:1:1:delete --config=segment.ms=10000 --config=min.cleanable.dirty.ratio=0.01 --config=min.compaction.lag.ms=1000 --config=retention.ms=20000 --config=delete.retention.ms=1000 --config=file.delete.delay.ms=1000"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
    phoebus-alarm-server:
        image: "pklaus/phoebus-alarm-server:4.6.3"
        command: "-noshell -server localhost:9092"
        network_mode: "host"
        depends_on: 
            - "kafka"